# Base
FROM python:3.14.0-alpine3.22

# Directorio de trabajo
WORKDIR /app

# Instalar dependencias sin cache
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la app
COPY . .

# Exponer el puerto que usará Gunicorn
EXPOSE 8000

# Comando para arrancar Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8000", "wsgi:app"]
